#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys

# add load path
if __name__ == "__main__":
    LIB_DIR = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
    if os.path.exists(os.path.join(LIB_DIR, "my_cookies")):
        sys.path.insert(0, LIB_DIR)


from my_cookies.my_cookies import main

main()
