;;; configs/~s/.doom.d/org-tags.el -*- lexical-binding: t; -*-

(setq org-tag-alist   '((:startgroup)
                        ("@personal" . nil)
                        (:grouptags)
                        ("@read" . ?r)
                        ("@school" . ?s)
                        ("@idea" . ?i)
                        ("@write" . ?w)
                        ("@check" . ?c)
                        ("@watch" . ?W)
                        (:endgroup)

                        (:startgroup)
                        ("@tinker" . nil)
                        (:grouptags)
                        ("@emacs" . ?e)
                        ("@blog" . ?b)
                        (:endgroup)

                        (:startgroup)
                        ("@nothing" . nil)
                        (:grouptags)
                        ("@chill" . ?C)
                        ("@lost" . ?l)
                        ("@people" . nil)
                        (:endgroup)
                        ;; topics
                        ("@politics" . nil)
                        ("@programming" . ?p)
                        ("@research" . ?R)
                        ("@philosophy" . nil)
                        ("@history" . nil)
                        ("@science" . nil)))
