#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc


# make sure You have installed the infinality patches

#export INFINALITY_FT_FILTER_PARAMS="8 17 50 17 8"
#export INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH="0"
#export INFINALITY_FT_FRINGE_FILTER_STRENGTH="55"
#export INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH="0"
#export INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH="0"
#export INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH="20"
#export INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH="0"
#export INFINALITY_FT_STEM_ALIGNMENT_STRENGTH="0"
#export INFINALITY_FT_STEM_FITTING_STRENGTH="100"
#export INFINALITY_FT_STEM_DARKENING_AUTOFIT="false"
#export INFINALITY_FT_STEM_DARKENING_CFF="false"
#export INFINALITY_FT_GAMMA_CORRECTION="0 100"
#export INFINALITY_FT_BRIGHTNESS="60"
#export INFINALITY_FT_CONTRAST="0"
#export INFINALITY_FT_USE_VARIOUS_TWEAKS="false"
#export INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS="false"
#export INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT="100"
#export INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE="0"
#export INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS="false"
#
#export INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE=35
#export INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE=0
#export INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE=0
#export INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE=0
