(add-to-list 'load-path "~/.doom.d/")
(require 'genset)
(require 'orgset)
(require 'languageshelpers)
(require 'packconf)
(require 'keys)
(require 'diredconf)
(require 'emailconf)
(require 'shellrc)
(require 'music)
(require 'feedreader)
