#
#Fri Jul 03 14:42:08 EEST 2026
PrivacyLinkPreviewsShowAlert=false
WhatsNewVersion=v6.5
AddressCreationCardShown=true
StoreDBPassphrase=false
AppUpdateNoticeShown=true
InitialRandomDBPassphrase=false
PrivacyDeliveryReceiptsSet=true
AppUpdateChannel=DISABLED
DesktopWindowState={\n    "width"\: 1470,\n    "height"\: 862,\n    "x"\: 1469,\n    "y"\: 868\n}
LANoticeShown=true
OneHandUICardShown=true
NewDatabaseInitialized=true
CurrentThemeIds={}
LastMigratedVersionCode=355
LiveMessageAlertShown=true
PrivacyLinkPreviews=true
ChatLastStart=1782472718157
ChatStopped=false
OnboardingStage=OnboardingComplete
