#
#Sun Sep 06 17:32:32 EEST 2026
PrivacyLinkPreviewsShowAlert=false
DesktopCloseBehavior=MinimizeToTray
WhatsNewVersion=v7.0
AddressCreationCardShown=true
StoreDBPassphrase=false
AppUpdateNoticeShown=true
InitialRandomDBPassphrase=false
PrivacyDeliveryReceiptsSet=true
ShowSubscriptionPercentage=true
AppUpdateChannel=DISABLED
DesktopWindowState={\n    "width"\: 833,\n    "height"\: 975,\n    "x"\: 15,\n    "y"\: 54\n}
LANoticeShown=true
OneHandUICardShown=true
NewDatabaseInitialized=true
CurrentThemeIds={}
LastMigratedVersionCode=366
LiveMessageAlertShown=true
PrivacyLinkPreviews=true
ChatLastStart=1788430048524
ChatStopped=false
OnboardingStage=OnboardingComplete
