#
#Sat Aug 15 05:27:43 EEST 2026
PrivacyLinkPreviewsShowAlert=false
DesktopCloseBehavior=MinimizeToTray
WhatsNewVersion=v7.0
AddressCreationCardShown=true
StoreDBPassphrase=false
AppUpdateNoticeShown=true
InitialRandomDBPassphrase=false
PrivacyDeliveryReceiptsSet=true
ShowSubscriptionPercentage=true
AppUpdateChannel=DISABLED
DesktopWindowState={\n    "width"\: 625,\n    "height"\: 1409,\n    "x"\: 1317,\n    "y"\: -1425\n}
LANoticeShown=true
OneHandUICardShown=true
NewDatabaseInitialized=true
CurrentThemeIds={}
LastMigratedVersionCode=366
LiveMessageAlertShown=true
PrivacyLinkPreviews=true
ChatLastStart=1786654215864
ChatStopped=false
OnboardingStage=OnboardingComplete
