#!/bin/bash

# Set decoration geometry
berryc border_width 5
berryc inner_border_width 3
berryc title_height 20
berryc top_gap 0

# Set decoration colors
berryc focus_color 23272E
berryc unfocus_color 23272E
berryc inner_focus_color 3F444A
berryc inner_unfocus_color 23272E
berryc text_focus_color ffffff
berryc text_unfocus_color eeeeee

# Other options
berryc smart_place "true"
berryc draw_text "true"
berryc edge_lock "false"
berryc set_font "PragmataPro"

berryc resize_mask "mod4"
berryc resize_button 3
berryc focus_follows_pointer false

sxhkd -c $HOME/.config/berry/sxhkdrc &
~/.dwm/autostart.sh

if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
        MONITOR=$m polybar --reload example &
    done
else
    polybar --reload example &
fi
